apiVersion: v1
kind: Service
metadata:
  annotations:
    ui: open-webui
  labels:
    ui: open-webui
  name: open-webui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    ui: open-webui
