apiVersion: v1
kind: Service
metadata:
  annotations:
    runtime: ollama
  labels:
    runtime: ollama
  name: ollama
spec:
  ports:
    - name: "11434"
      port: 11434
      targetPort: 11434
  selector:
    runtime: ollama
